services:
  ollama:
    deploy: null
    environment:
      CUDA_VISIBLE_DEVICES: ""
      OLLAMA_MAX_LOADED_MODELS: 1

  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    deploy: null
    environment:
      CUDA_VISIBLE_DEVICES: ""
