services:
  mcp-currency:
    extends:
      file: compose.spring.yaml
      service: mcp-currency

  mcp-filesystem:
    extends:
      file: compose.spring.yaml
      service: mcp-filesystem

  mcp-weather:
    extends:
      file: compose.spring.yaml
      service: mcp-weather

  minio:
    extends:
      file: compose.spring.yaml
      service: minio

  ollama:
    extends:
      file: compose.spring.yaml
      service: ollama
    deploy: null
    environment:
      CUDA_VISIBLE_DEVICES: ""
      OLLAMA_MAX_LOADED_MODELS: 1

  qdrant:
    extends:
      file: compose.spring.yaml
      service: qdrant

  speaches:
    extends:
      file: compose.spring.yaml
      service: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    deploy: null
    environment:
      CUDA_VISIBLE_DEVICES: ""

volumes:
  minio_data:
    name: sa_minio_data
  ollama_data:
    name: sa_ollama_data
  qdrant_data:
    name: sa_qdrant_data
  speaches_data:
    name: sa_speaches_data
