services:
  ollama:
    build:
      dockerfile: ${PWD}/docker/ollama/Dockerfile
    ports:
      - "11434"
    restart: unless-stopped
    environment:
      OLLAMA_NUM_PARALLEL: 2
      OLLAMA_MAX_LOADED_MODELS: 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'curl -fs localhost:11434 | grep -q "Ollama is running" || exit 1',
        ]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    build:
      dockerfile: ${PWD}/docker/qdrant/Dockerfile
    ports:
      - "6333"
      - "6334"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'curl -fs localhost:6333/healthz | grep -q "healthz check passed" || exit 1',
        ]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  spring-ai:
    image: spring-ai:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: default, docker
      JAVA_TOOL_OPTIONS: |
        -Dspring.aot.enabled=false
        -XX:+UseG1GC
        -XX:+UseStringDeduplication
    deploy:
      resources:
        limits:
          memory: 1g
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'wget -qO- localhost/actuator/health/liveness | grep -q "UP" || exit 1',
        ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    name: ollama_data
