services:
  minio:
    extends:
      file: compose.yaml
      service: minio
    profiles:
      - minio

  ollama:
    extends:
      file: compose.yaml
      service: ollama
    profiles:
      - ollama

  qdrant:
    extends:
      file: compose.yaml
      service: qdrant
    profiles:
      - qdrant

volumes:
  minio_data:
    name: minio_data
  ollama_data:
    name: ollama_data
  qdrant_data:
    name: qdrant_data
