services:
  mcp-currency:
    extends:
      file: compose.spring.yaml
      service: mcp-currency

  mcp-filesystem:
    extends:
      file: compose.spring.yaml
      service: mcp-filesystem

  mcp-weather:
    extends:
      file: compose.spring.yaml
      service: mcp-weather

  minio:
    extends:
      file: compose.spring.yaml
      service: minio

  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - nvidia.com/gpu=all
              driver: cdi
    environment:
      OLLAMA_MAX_LOADED_MODELS: 2
    extends:
      file: compose.spring.yaml
      service: ollama

  qdrant:
    extends:
      file: compose.spring.yaml
      service: qdrant

  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cuda-12.6.3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - nvidia.com/gpu=all
              driver: cdi
    extends:
      file: compose.spring.yaml
      service: speaches

volumes:
  minio_data:
    name: sa_minio_data
  ollama_data:
    name: sa_ollama_data
  qdrant_data:
    name: sa_qdrant_data
  speaches_data:
    name: sa_speaches_data
