services:
  ollama:
    extends:
      file: compose.yaml
      service: ollama
    profiles:
      - ollama

  postgres:
    extends:
      file: compose.yaml
      service: postgres
    profiles:
      - postgres

volumes:
  ollama_data:
    name: ollama_data
