file:
  supplier:
    directory: ${INGEST_DIR}
    filename-regex: ${INGEST_FILES_FILTER}
logbook:
  format:
    style: http
logging:
  include-application-name: false
  level:
    com.hamza: debug
    org.hibernate:
      SQL: debug
      stat: debug
    org.zalando.logbook: trace
management:
  endpoint:
    env:
      show-values: always
    health:
      group:
        readiness:
          include: "*"
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
server:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/x-ndjson,application/xml,text/css,text/event-stream,text/html,text/javascript,text/plain,text/xml
    min-response-size: 1500B
  forward-headers-strategy: native
  http2:
    enabled: true
  port: 8080
  ssl:
    enabled: false
spring:
  ai:
    ollama:
      chat:
        model: ${OLLAMA_MODEL}
        temperature: ${OLLAMA_TEMPERATURE}
        top-k: ${OLLAMA_TOP_K} # how many of most similar documents to return at most
        top-p: ${OLLAMA_TOP_P}
      embedding:
        model: ${OLLAMA_EMBEDDING_MODEL}
      init:
        pull-model-strategy: when_missing
    vectorstore:
      qdrant:
        collection-name: embeddings
        initialize-schema: true
  application:
    name: spring-ai
  cloud:
    function:
      definition: fileSupplier|duplicationFilter|documentReader|documentSplitter|vectorStoreWriter
  config:
    activate:
      on-profile: default
    import:
      - optional:file:.env[.properties]
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    driverClassName: org.h2.Driver
    password: ${DB_PASSWORD}
    url: jdbc:h2:mem:${DB_NAME}
    username: ${DB_USER}
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: compose.spring.yaml
      profiles:
        active:
          - ollama
          - qdrant
      start:
        arguments:
          - --remove-orphans
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        batch_fetch_style: dynamic
        cache:
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          use_query_cache: true
          use_second_level_cache: true
        default_batch_fetch_size: 32
        enable_lazy_load_no_trans: false
        format_sql: false
        generate_statistics: true
        globally_quoted_identifiers: true
        javax:
          cache:
            missing_cache_strategy: fail
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml
        jdbc:
          batch_size: 32
        jpa:
          compliance:
            query: false
        max_fetch_depth: 1
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: "100"
        show_sql: false
  main:
    banner-mode: off
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
  sql:
    init:
      mode: never
  threads:
    virtual:
      enabled: true
  web:
    error:
      include-exception: true
      include-message: always
      include-stacktrace: always
springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  packagesToScan: com.hamza
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    operationsSorter: method
    path: /swagger-ui
    tagsSorter: alpha
---
file:
  supplier:
    directory: /home/${INGEST_DIR}
server:
  compression:
    enabled: false
  port: 80
spring:
  ai:
    ollama:
      base-url: http://ollama:11434
    vectorstore:
      qdrant:
        host: qdrant
  config:
    activate:
      on-profile: container
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
---
logging:
  level:
    root: OFF
server:
  port: 8013
spring:
  config:
    activate:
      on-profile: openapi
  docker:
    compose:
      enabled: false
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  packagesToScan: com.hamza
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    operationsSorter: method
    path: /swagger-ui
    tagsSorter: alpha
