custom:
  weather:
    api: https://wttr.in
logging:
  include-application-name: false
  level:
    root: error
spring:
  ai:
    mcp:
      server:
        name: weather
        stdio: true
        type: sync
  application:
    name: mcp-weather
  config:
    activate:
      on-profile: default
  main:
    banner-mode: off
  output:
    ansi:
      enabled: never
  threads:
    virtual:
      enabled: true
