custom:
  memory:
    store: chat_memory
  supplier:
    filename-regex: ${INGEST_FILES_FILTER}
    pipeline-timeout: 600000
    polling-interval: ${INGEST_POLL_INTERVAL}
    remote-dir: ${MINIO_DEFAULT_BUCKET}
logbook:
  format:
    style: http
  predicate:
    exclude:
      - path: /actuator/**
      - path: /api-docs/**
      - path: /swagger-ui/**
logging:
  include-application-name: false
  level:
    com.hamza: trace
    org.hibernate:
      SQL: debug
      stat: debug
    org.springframework.ai.rag: debug
    org.zalando.logbook: trace
management:
  endpoint:
    env:
      show-values: always
    health:
      group:
        readiness:
          include: "*"
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  opentelemetry:
    tracing:
      export:
        otlp:
          compression: gzip
          endpoint: http://localhost:4317
          transport: grpc
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    propagation:
      type: B3
    sampling:
      probability: 1
server:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/x-ndjson,application/xml,text/css,text/event-stream,text/html,text/javascript,text/plain,text/xml
    min-response-size: 1500B
  forward-headers-strategy: native
  http2:
    enabled: true
  port: 8080
  ssl:
    enabled: false
spring:
  ai:
    chat:
      client:
        observations:
          log-completion: true
          log-prompt: true
      memory:
        repository:
          jdbc:
            initialize-schema: always
      observations:
        include-error-logging: true
        log-completion: true
        log-prompt: true
    image:
      observations:
        log-prompt: true
    mcp:
      client:
        streamable-http:
          connections:
            mcp-currency:
              url: http://localhost:3002
            mcp-filesystem:
              url: http://localhost:3000
            mcp-weather:
              url: http://localhost:3001
        type: async
    model:
      chat: ollama
      embedding: ollama
    ollama:
      chat:
        model: ${OLLAMA_MODEL}
        temperature: ${OLLAMA_TEMPERATURE}
        top-k: ${OLLAMA_TOP_K} # how many of most similar documents to return at most
        top-p: ${OLLAMA_TOP_P}
      embedding:
        model: ${OLLAMA_EMBEDDING_MODEL}
      init:
        pull-model-strategy: when_missing
    openai:
      api-key: fake
      audio:
        speech:
          model: tts
          response-format: mp3
          speed: 1.0
        transcription:
          model: stt
      base-url: http://localhost:8000/v1
    tools:
      observations:
        include-content: true
    vectorstore:
      observations:
        log-query-response: true
      qdrant:
        collection-name: embeddings
        host: localhost
        initialize-schema: true
  application:
    name: spring-ai
  cloud:
    aws:
      credentials:
        access-key: ${MINIO_ROOT_USER}
        secret-key: ${MINIO_ROOT_PASSWORD}
      region:
        static: us-east-1
      s3:
        enabled: true
        endpoint: http://localhost:9000
        path-style-access-enabled: true
    function:
      definition: customS3Supplier|duplicationFilter|documentReader|documentSplitter|vectorStoreWriter|s3Archiver
  config:
    activate:
      on-profile: default
    import:
      - optional:file:.env[.properties]
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    driverClassName: org.h2.Driver
    password: ${DB_PASSWORD}
    url: jdbc:h2:file:~/${DB_NAME}
    username: ${DB_USER}
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: compose.spring.yaml
      profiles:
        active:
          - grafana
          - jaeger
          - mcp-currency
          - mcp-filesystem
          - mcp-weather
          - minio
          - ollama
          - prometheus
          - qdrant
          - speaches
      start:
        arguments:
          - --remove-orphans
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        batch_fetch_style: dynamic
        cache:
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          use_query_cache: true
          use_second_level_cache: true
        default_batch_fetch_size: 32
        enable_lazy_load_no_trans: false
        format_sql: false
        generate_statistics: true
        globally_quoted_identifiers: true
        javax:
          cache:
            missing_cache_strategy: fail
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml
        jdbc:
          batch_size: 32
        jpa:
          compliance:
            query: false
        max_fetch_depth: 1
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: "100"
        show_sql: false
  main:
    banner-mode: off
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
  reactor:
    context-propagation: auto
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      mode: never
  threads:
    virtual:
      enabled: true
  web:
    error:
      include-exception: true
      include-message: always
      include-stacktrace: always
springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.hamza
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    operationsSorter: method
    path: /swagger-ui
    tagsSorter: alpha
tracing:
  excludeUris:
    - /actuator
    - /api-docs
    - /swagger-ui
---
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://jaeger:4317
server:
  compression:
    enabled: false
  port: 80
spring:
  ai:
    mcp:
      client:
        streamable-http:
          connections:
            mcp-currency:
              url: http://mcp-currency:80
            mcp-filesystem:
              url: http://mcp-filesystem:3000
            mcp-weather:
              url: http://mcp-weather:3000
    ollama:
      base-url: http://ollama:11434
    openai:
      base-url: http://speaches:8000/v1
    vectorstore:
      qdrant:
        host: qdrant
  cloud:
    aws:
      s3:
        endpoint: http://minio:9000
  config:
    activate:
      on-profile: container
  datasource:
    url: jdbc:h2:file:/data/${DB_NAME}
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
---
custom:
  memory:
    store: no
  supplier:
    filename-regex: no
    pipeline-timeout: 999999999
    polling-interval: 9999999999
    remote-dir: no
logging:
  level:
    root: off
management:
  server:
    port: -1
server:
  port: 7355
spring:
  ai:
    model:
      chat: noOpChatModel
      embedding: noOpEmbeddingModel
    openai:
      api-key: false
  cloud:
    aws:
      s3:
        enabled: false
  config:
    activate:
      on-profile: openapi-plugin
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
  main:
    banner-mode: off
  output:
    ansi:
      enabled: never
springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  packagesToScan: com.hamza
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    enabled: false
    operationsSorter: method
    path: /swagger-ui
    tagsSorter: alpha
---
spring:
  config:
    activate:
      on-profile: gpu
  docker:
    compose:
      file: compose.spring.gpu.yaml
---
custom:
  h2:
    port: 9092
spring:
  config:
    activate:
      on-profile: h2-tcp
